package com.coronation.collections.domain.enums;

/**
 * Created by Toyin on 4/12/19.
 */
public enum TaskType {
    CREATE_USER, EDIT_USER, DELETE_USER, ASSIGN_ROLE, VIEW_USERS, CREATE_ROLE, ADD_ROLE_TASK,
    DELETE_ROLE_TASK, CREATE_TASK, EDIT_TASK, VIEW_TASKS, CREATE_ACCOUNT, EDIT_ACCOUNT, APPROVE_ACCOUNT,
    FETCH_ACCOUNT, CREATE_BANK, CREATE_PRODUCT, EDIT_PRODUCT, EDIT_PRODUCT_ACCOUNT, APPROVE_PRODUCT,
    APPROVE_PRODUCT_ACCOUNT, REVERT_PRODUCT, DELETE_PRODUCT, VIEW_PRODUCTS
}
