package com.coronation.collections.domain.enums;

/**
 * Created by Toyin on 4/12/19.
 */
public enum TaskType {
    CREATE_USER, EDIT_USER, DELETE_USER, ASSIGN_ROLE, VIEW_USERS, CREATE_ROLE, ADD_ROLE_TASK, VIEW_ROLES, EDIT_ROLE,
    DELETE_ROLE_TASK, CREATE_TASK, EDIT_TASK, VIEW_TASKS, CREATE_ACCOUNT, EDIT_ACCOUNT, APPROVE_ACCOUNT,
    VIEW_ACCOUNTS, CREATE_BANK, CREATE_PRODUCT, EDIT_PRODUCT, EDIT_PRODUCT_ACCOUNT, APPROVE_PRODUCT, DELETE_ACCOUNT,
    APPROVE_PRODUCT_ACCOUNT, REVERT_PRODUCT, DELETE_PRODUCT, VIEW_PRODUCTS, INITIATE_PAYMENT, APPROVE_PAYMENT,
    EDIT_PAYMENT, CANCEL_PAYMENT, REVERT_PAYMENT, CONFIRM_PAYMENT, MAKE_PAYMENT, MARK_PAYMENT_PAYABLE,
    DELETE_PAYMENT, SET_DISTRIBUTOR_ACCOUNT, VALIDATE_PAYMENT, VIEW_PAYMENTS, UPLOAD_PAYMENTS, VIEW_REPORTS,
    CREATE_DISTRIBUTOR, APPROVE_DISTRIBUTOR, ADD_MERCHANT_DISTRIBUTOR, EDIT_DISTRIBUTOR, DELETE_DISTRIBUTOR,
    VIEW_DISTRIBUTORS, ADD_DISTRIBUTOR_USER, ADD_MERCHANT, EDIT_MERCHANT, DELETE_MERCHANT, ACTIVATE_MERCHANT, VIEW_MERCHANTS,
    APPROVE_MERCHANT, ADD_MERCHANT_USER, MANAGE_API_KEYS,VIEW_MERCHANT_USERS, CREATE_ORGANIZATION, EDIT_ORGANIZATION,
    DELETE_ORGANIZATION, ACTIVATE_ORGANIZATION, VIEW_ORGANIZATIONS, ADD_ORGANIZATION_USER, MANAGE_ACCESS
}
